services:
  - type: static
    name: base-frontend
    env: static
    buildCommand: npm ci && npm run build
    publishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /api/*
        destination: https://base-backend-ep08.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
